[package]
name = "migration"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
sea-orm-migration = { version = "2", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
uuid = { version = "1", features = ["v4"] }
